### ISSUE TITLE
FF14 only shows logo 

### ISSUE THREAD

**Issue by Skyy93** [Moosatronic/LinuxFFXIVProtonFix#12]
hey, first of all thank you very much for your script! 

Unfortunately, Final Fantasy starts but only the logo is displayed with a grey screen and the launcher itself does not appear. Is this a known problem and if so is there a solution?

**Comment by Centzilius** [comment]
In that case you have not selected the correct compatibility tool / have not modified it. Only showing the logo indicates that the original new launcher started. If you need further help please reach out here: https://discord.gg/sV4nQaR4

**Comment by Skyy93** [comment]
i will try again, thank you if i need further help i reach out via discord
