### ISSUE TITLE
Re: Proton 5

### ISSUE THREAD

**Issue by Moosatronic** [Moosatronic/LinuxFFXIVProtonFix#2]
Is Proton 5 really necessary for Centzilius's script as a dependency?

It's my understanding that the protonfix required either winetricks or proton5 so I want to confirm what is truly necessary.

**Comment by Centzilius** [comment]
Testing has shown that running the winetricks verb to install dotnet48 is more likely to succeed if it uses Proton 5.0. Personally I also had success by using `util.protontricks('dotnet48')` but others had issues with that.
util.install_dotnet automatically uses proton 5 in Proton-6.21-GE-2.
